#!/bin/sh
set -e

# Finish removing the obsolete 0666 udev rule from versions <= 0.1.2
dpkg-maintscript-helper rm_conffile \
    /lib/udev/rules.d/99-antec-flux-pro-display.rules 0.1.3~ -- "$@"

# Reload systemd daemon
systemctl daemon-reload || true

#DEBHELPER#
