#!/bin/sh
set -e

# Stop service before removal
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
    systemctl stop antec-flux-pro-display.service || true
    systemctl disable antec-flux-pro-display.service || true
fi

#DEBHELPER#